name: Run and Build unit tests

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup .NET version 6
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 6.0.x

      - name: Restore dependancies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Unit Tests execution
        run: dotnet test HouseRentingSystem.UnitTests/HouseRentingSystem.UnitTests.csproj --no-build --verbosity normal
        
